### ISSUE TITLE
Add support for wdio v5

### ISSUE THREAD

**Issue by petrosbountis** [rhysd/wdio-appium-service#12]
This project does not support the [new version](https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html) of WebdriverIO.

@rhysd is there any plan on making it compatible with v5?

Thanks in advance.

**Comment by sanyco92** [comment]
+1, please make compatible with wdio 5

**Comment by MortenGregersen** [comment]
What needs to be done to support wdio v5?

**Comment by baruchvlz** [comment]
WebdriverIO has an open issue to port this library into the core packages. This would be a lot easier to do than convince someone to update a library that hasn't been touched in 2 years. https://github.com/webdriverio/webdriverio/issues/3693

**Comment by MortenGregersen** [comment]
I'm working on porting this service to the wdio mono repo (webdriverio/webdriverio/issues/3693)

**Comment by christian-bromann** [comment]
We have absorbed the project into the WebdriverIO org. I recommend to use `@wdio/appium-service` from now on.
